language: python
python:
  - "2.7"
script:
  - pip install coveralls
  - pip install coverage
  - pip install nose
  - pip install glob2
  - pip install configparser
  - "sudo easy_install pip"
  - "sudo apt-get -y install w3m"
  - "sudo pip install glob2 --upgrade"
  - "sudo pip install configparser --upgrade"
  - "sudo apt-get install python python-tk idle python-pmw python-imaging"
  - "sudo chmod +x SimplyTemplate.py"
  - "sudo ./SimplyTemplate.py -l -v"
  - "sudo ./SimplyTemplate.py -h"
  - nosetests --with-coverage
after_success:
  - coveralls
